[package]
name = "lean-monotone"
version = "0.1"
lean_version = "master"

[dependencies]
lean-tidy = {git = "git@github.com:semorrison/lean-tidy.git", rev = "47c92fec49df7274f37a9ce14c06c345aea66a21"}
